import Head from "next/head";
import Navbar from "../components/Navbar";
import Token from "../components/Token";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Maker Teleport UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Token />
      </main>
    </div>
  );
}
